version: '3.8'

services:

  tomcat:
    build:
      context: .
      args:
        AXELOR_VERSION: ${VERSION}
        AXELOR_DB_USER: ${DB_USER}
        AXELOR_DB_PASSWORD: ${DB_PASSWORD}
        AXELOR_DB_URL: jdbc:postgresql:\/\/postgres:5432\/${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:9
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - backup_db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  backup_db:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge